service: orchestrator

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:ListFunctions
            - lambda:GetFunctionConfiguration
            - lambda:UpdateFunctionConfiguration
          Resource:
            - "*"

functions:
  herokuTrigger:
    handler: handler.herokuTrigger
    events:
      - http: 
          path: heroku
          method: post
          cors: true

plugins:
  - serverless-bundle
