AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  media-lambda
  Sample SAM Template for media-lambda

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: index.handler
      Runtime: nodejs14.x