service: community-metrics

frameworkVersion: '3'
useDotenv: true

custom:
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux sharp
    packager: yarn
    ignorePackages:
      - pg-native
    forceInclude:
      - pg
      - pg-hstore
  webpack:
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}

functions:
  calcuateCommunitiesMetrics:
    handler: handler.calculate
    events:
      - schedule: cron(0 0 * * ? *)
      - schedule: cron(30 2 * * ? *)
      - schedule: cron(30 4 * * ? *)
      - schedule: cron(30 6 * * ? *)

  updateUBIState:
    handler: handler.ubiState
    events:
      - schedule: rate(2 hours)

plugins:
  - serverless-webpack
