service: media-lambda

frameworkVersion: '3'

custom:
  bucket: bucket-test-jp2
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux sharp
    packager: yarn
    ignorePackages:
      - pg-native

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.bucket}/*"
functions:
  media:
    handler: handler.media
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          existing: true

plugins:
  - serverless-bundle