service: update-borrowers

frameworkVersion: '3'
useDotenv: true

custom:
  bundle:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux sharp
    packager: yarn
    ignorePackages:
      - pg-native
    forceInclude:
      - pg
      - pg-hstore
  webpack:
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}

functions:
  updateBorrowers:
    handler: handler.start
    events:
      # Invoke Lambda function every 30 minutes
      - schedule: cron(30 * * * * *)

plugins:
  - serverless-webpack
